/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.loginCliente;

import control.ClienteController;
import control.SessaoClienteController;
import java.awt.event.KeyEvent;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import model.Cliente;
import view.carrinho.CarrinhoView;
import view.loginUsuario.AutenticacaoUserView;

/**
 *
 * @author Leo
 */
public class LoginClienteView extends javax.swing.JFrame {

    /**
     * Creates new form LoginClienteView
     */
    public LoginClienteView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jtfNome = new javax.swing.JTextField();
        jtfCPF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jbtLogar = new javax.swing.JButton();
        jbtCancelar = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        jLabel4.setText("jLabel4");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                formKeyPressed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Easy Market");

        jtfNome.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfNomeKeyPressed(evt);
            }
        });

        jtfCPF.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jtfCPFKeyPressed(evt);
            }
        });

        jLabel2.setText("Nome");

        jLabel3.setText("CPF");

        jbtLogar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/OK.png"))); // NOI18N
        jbtLogar.setText("Iniciar as compras");
        jbtLogar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtLogarActionPerformed(evt);
            }
        });

        jbtCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/img/Abort.png"))); // NOI18N
        jbtCancelar.setText("Cancelar");
        jbtCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtCancelarActionPerformed(evt);
            }
        });

        jLabel5.setText("Entre com seus dados para iniciar a compra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(167, Short.MAX_VALUE)
                .addComponent(jbtLogar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbtCancelar)
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel2))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addGap(70, 70, 70)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtfCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 50, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbtLogar)
                    .addComponent(jbtCancelar))
                .addGap(19, 19, 19))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jbtLogarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtLogarActionPerformed
        //Verifica se o CPF existe no banco
        Cliente c = new Cliente();

        try {
            c = ClienteController.getInstance().buscarCPF(jtfCPF.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro na busca");
        }

        try {

            if (c == null) {//Realiza novo cadastro e loga o usuario

                try {
                        // Pega os dados informados nos campos cria um objeto produto e dispara o metodo de persitêcia na tela 

                        ClienteController.getInstance().persistir(getDados());
                        SessaoClienteController.getInstance().setCliente(getDados());

                        JOptionPane.showMessageDialog(this, "Olá, bem vindo ao Easy Market");
                        CarrinhoView v = new CarrinhoView();
                        v.setLocationRelativeTo(null);
                        v.setVisible(true);
                        this.setVisible(false);

                } catch (Exception ex) {
                    JOptionPane.showMessageDialog(this, "Ocorreu o seguinte erro na gravação dos dados: " + ex.getMessage());
                }

            } else {//Cria sessao e redireciona
                SessaoClienteController.getInstance().setCliente(c);

                CarrinhoView v = new CarrinhoView();
                v.setLocationRelativeTo(null);
                v.setVisible(true);
                this.setVisible(false);
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Erro no processo");
        }
    }//GEN-LAST:event_jbtLogarActionPerformed

    private void jbtCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtCancelarActionPerformed
        dispose();
    }//GEN-LAST:event_jbtCancelarActionPerformed

    private void formKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_formKeyPressed
        if (evt.getKeyCode() == evt.VK_F2) {
            AutenticacaoUserView v = new AutenticacaoUserView();
            v.setLocationRelativeTo(null);
            v.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_formKeyPressed

    private void jtfNomeKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfNomeKeyPressed
        if (evt.getKeyCode() == evt.VK_F2) {
            AutenticacaoUserView v = new AutenticacaoUserView();
            v.setLocationRelativeTo(null);
            v.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jtfNomeKeyPressed

    private void jtfCPFKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCPFKeyPressed
        if (evt.getKeyCode() == evt.VK_F2) {
            AutenticacaoUserView v = new AutenticacaoUserView();
            v.setLocationRelativeTo(null);
            v.setVisible(true);
            this.setVisible(false);
        }
    }//GEN-LAST:event_jtfCPFKeyPressed

    /**
     * Pega os dados dos componentes da View e joga para o objeto Cliente
     *
     * @return Cliente
     */
    public Cliente getDados() {

        Cliente c = new Cliente();

        c.setNome(jtfNome.getText());
        c.setCpf(jtfCPF.getText());

        return c;
    }

    //Validação dos campos em obrigatórios
    private boolean validation() {
        if (jtfNome.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo nome é obrigatório.");
            jtfNome.requestFocus();
            return false;
        }

        if (jtfCPF.getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo CPF é obrigatório.");
            jtfCPF.requestFocus();
            return false;
        }

        return true;
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginClienteView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                LoginClienteView v = new LoginClienteView();
                v.setLocationRelativeTo(null);
                v.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JButton jbtCancelar;
    private javax.swing.JButton jbtLogar;
    private javax.swing.JTextField jtfCPF;
    private javax.swing.JTextField jtfNome;
    // End of variables declaration//GEN-END:variables
}
