/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.carrinho;

import control.ItemCarrinhoController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Carrinho;
import model.ItemCarrinho;
import util.DateTimeUtil;

/**
 *
 * @author Leo
 */
public class DetalhesCarrinhoView extends javax.swing.JFrame {

    /**
     * Creates new form DetalhesCarrinhoView
     */
    public DetalhesCarrinhoView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jlbID = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jlbData = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jlbCliente = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jlbValor = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtProdutos = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosed(java.awt.event.WindowEvent evt) {
                formWindowClosed(evt);
            }
        });

        jLabel1.setText("Compra");

        jlbID.setText("jLabel2");

        jLabel3.setText("Data");

        jlbData.setText("jLabel4");

        jLabel5.setText("Cliente");

        jlbCliente.setText("jLabel6");

        jLabel7.setText("Produtos");

        jLabel8.setText("Valor Total");

        jlbValor.setText("jLabel9");

        jtProdutos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(jtProdutos);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 366, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 14, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jlbCliente))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jlbData)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbID)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jlbValor)
                        .addGap(73, 73, 73))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jlbID)
                    .addComponent(jLabel8)
                    .addComponent(jlbValor))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jlbData))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jlbCliente))
                .addGap(25, 25, 25)
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 152, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowClosed(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosed
       //Em desenvolvimento
        DetalhesCarrinhoView.this.dispose();
    }//GEN-LAST:event_formWindowClosed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DetalhesCarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DetalhesCarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DetalhesCarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DetalhesCarrinhoView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DetalhesCarrinhoView().setVisible(true);
            }
        });
    }

    /**
     * Seta os dados do objeto Carrinho para os componentes da tela.
     *
     * @param carrinho
     */
    public void setDados(Carrinho carrinho) {

        jlbID.setText(carrinho.getId().toString());
        jlbData.setText(DateTimeUtil.getInstance().parseDate(carrinho.getData()));
        jlbCliente.setText(carrinho.getCliente().getNome());

        ListarCompras(carrinho.getId());

    }

    //Lista produtos(itens)
    private void ListarCompras(Long id_carrinho) {
        List<ItemCarrinho> item = ItemCarrinhoController.getInstance().BuscaPorCarrinho(id_carrinho);

        // Cria um defaultTableModel para ser usado na JTable com os campos que serão exibidos na tela
        DefaultTableModel modelo = new DefaultTableModel();
        modelo.addColumn("Produto");
        modelo.addColumn("Quantidade");
        modelo.addColumn("Valor");

        for (ItemCarrinho i : item) {
            // Seta os valores do objeto para o JTableModel 
            modelo.addRow(new Object[]{i.getProduto().getNome(),i.getQuantidade(),i.getValor()});
        }
        //Limpa a JTable (Grid)
        jtProdutos.removeAll();
        //Seta o modelo para a Grid 
        jtProdutos.setModel(modelo);

        //Ajusta o tamanho da primeira coluna 
        jtProdutos.getColumnModel().getColumn(0).setPreferredWidth(180);
        jtProdutos.getColumnModel().getColumn(1).setPreferredWidth(60);
        jtProdutos.getColumnModel().getColumn(2).setPreferredWidth(60);

        //Ocutar coluna ID 
        ///jtAluno.getColumnModel().getColumn(0).setMinWidth(0);
        //jtAluno.getColumnModel().getColumn(0).setMaxWidth(0);
        //jtAluno.getColumnModel().getColumn(0).setWidth(0);
        jlbValor.setText(CalculaTotal());
    }
    
    
    private String CalculaTotal() {
        Double Orcamento = 0.0;
        for (int i = 0; i < jtProdutos.getRowCount(); i++) {
            Orcamento += Double.parseDouble(jtProdutos.getValueAt(i, 2).toString());
        }
        return Orcamento.toString();
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlbCliente;
    private javax.swing.JLabel jlbData;
    private javax.swing.JLabel jlbID;
    private javax.swing.JLabel jlbValor;
    private javax.swing.JTable jtProdutos;
    // End of variables declaration//GEN-END:variables
}
